import Link from 'next/link'


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  console.log("montando layout")
  return (
    <html lang="en">
      <body>
        {children}
        <div>
          <h2>Esta página tem dedo do layout principal</h2>
          <Link href="/novarota">Rota1</Link> <br/><br/>
          <a href="/novarota">Rota 1, jeito antigo</a>
        </div>
        </body>
    </html>
  )
}
